# ??????
spring.datasource.url=jdbc:mysql://localhost:3306/dhc_pms_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=root

# ????
logging.level.com.example.dhcpms=debug

# Swagger??
swagger.enabled=true
